# -*- coding: utf-8 -*-
"""week06_portfolio_contact_book.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cpQ3bImlhCVthP-TYnEF76NFYMoUE9ON
"""

contacts={
    "Pra" : "0450 1234",
    "Ram" : "0450 3456",
    "Sam" : "0450 0987"
}
contacts["Hari"] = "0450 7898"
contacts["Pra"] = "0450 7777"

for key, value in contacts.items():
  print(key,value)

contacts={
  "Pra" : {
      "phone" : "0450 1234",
      "email" : "pra@gmail.com"
  },
    "Ram" : {
        "phone" : "0450 3456",
        "email" : "ram@gmail.com"
    },
    "Sam" : {
        "phone" : "0450 0987",
        "email" : "sam@gmail.com"
    }
}

for key, value in contacts.items():
  print("-" * 40)
  print("Name :", key)
  print("Phone :",value["phone"] )
  print("Email :",value["email"] )
print("-" * 40)

name = input("Enter your name : ")
if name in contacts:
  print("Phone:", contacts[name]["phone"])
  print("Email:", contacts[name]["email"])
else:
  print("Contact not found")